package data;

import LOGIN.LOGI;
import java.io.PrintStream;
import java.io.UnsupportedEncodingException;
import java.nio.charset.StandardCharsets;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mario
 */
public class data1 extends javax.swing.JFrame {

    /**
     * Creates new form data1
     */
    public data1() {
        initComponents();
        try {
            System.setOut(new PrintStream(System.out, true, StandardCharsets.UTF_8.name()));
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(data1.class.getName()).log(Level.SEVERE, null, ex);
        }
        er.setVisible(false);
        er2.setVisible(false);

        nametxt.setBackground(new java.awt.Color(0, 0, 0, 1));
        phonetxt.setBackground(new java.awt.Color(0, 0, 0, 1));
        addresstxt.setBackground(new java.awt.Color(0, 0, 0, 1));
        s1.setVisible(false);
        jButton6.setBackground(new java.awt.Color(0, 0, 0, 1));
        ok_delete.setBackground(new java.awt.Color(0, 0, 0, 1));
        ser.setBackground(new java.awt.Color(0, 0, 0, 1));
        searchEdite.setBackground(new java.awt.Color(0, 0, 0, 1));
        t.setBackground(new java.awt.Color(0, 0, 0, 1));
        U.setBackground(new java.awt.Color(0, 0, 0, 1));
        ok.setBackground(new java.awt.Color(0, 0, 0, 1));

        //--------------------------------------------
        ch.setVisible(false);
        nametxt.setVisible(false);
        phonetxt.setVisible(false);
        addresstxt.setVisible(false);
        jDateChooser1.setVisible(false);
        Health_psychological_problemstxt.setVisible(false);
        yesornocom.setVisible(false);
        year_it_verticalcom.setVisible(false);
        addstu.setVisible(false);
        jLabel8.setVisible(false);
        jLabel10.setVisible(false);
        jLabel12.setVisible(false);
        jLabel13.setVisible(false);
        jLabel14.setVisible(false);
        jLabel15.setVisible(false);
        jLabel16.setVisible(false);
        jLabel17.setVisible(false);
        jLabel18.setVisible(false);
        enter.setVisible(false);
        ok_delete.setVisible(false);
        ok_delete.setEnabled(false);
        ser.setVisible(false);
        searchEdite.setVisible(false);
        serEdLable.setVisible(false);
        serEdLable2.setVisible(false);
        SAVE.setVisible(false);
        UPDATE.setVisible(false);
        BACK.setVisible(false);
        t.setVisible(false);
        ok.setVisible(false);
        U.setVisible(false);
        addICON.setVisible(false);
        del_ICON.setVisible(false);
        sa_ICON.setVisible(false);
        UP_ICON.setVisible(false);
        veiw_icon.setVisible(false);
        POINT.setVisible(false);
        jTextField1.setVisible(false);
        po_txt.setVisible(false);
        jTextField3.setVisible(false);
        jTextField1.setEditable(false);
        jTextField3.setEditable(false);
        plus_5_bu.setVisible(false);
        plus_5_la.setVisible(false);
        plus_5_la2.setVisible(false);
        munis_5_bu1.setVisible(false);
        munis_5_la1.setVisible(false);
        munis_5_la3.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ch = new javax.swing.JPanel();
        enter = new javax.swing.JLabel();
        addMan = new javax.swing.JLabel();
        tu = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        er2 = new javax.swing.JLabel();
        er = new javax.swing.JLabel();
        sidepanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        back_io = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        s1 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();
        del_ICON = new javax.swing.JLabel();
        veiw_icon = new javax.swing.JLabel();
        addresstxt = new javax.swing.JTextField();
        nametxt = new javax.swing.JTextField();
        phonetxt = new javax.swing.JTextField();
        addICON = new javax.swing.JLabel();
        U = new javax.swing.JButton();
        ok = new javax.swing.JButton();
        year_it_verticalcom = new javax.swing.JComboBox<>();
        yesornocom = new javax.swing.JComboBox<>();
        addstu = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        po_txt = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        POINT = new javax.swing.JLabel();
        BACK = new javax.swing.JButton();
        Health_psychological_problemstxt = new javax.swing.JTextArea();
        ok_delete = new javax.swing.JButton();
        ser = new javax.swing.JButton();
        searchEdite = new javax.swing.JTextField();
        serEdLable = new javax.swing.JLabel();
        serEdLable2 = new javax.swing.JLabel();
        sa_ICON = new javax.swing.JLabel();
        SAVE = new javax.swing.JButton();
        UP_ICON = new javax.swing.JLabel();
        UPDATE = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        t = new javax.swing.JTextField();
        plus_5_la = new javax.swing.JLabel();
        plus_5_la2 = new javax.swing.JLabel();
        plus_5_bu = new javax.swing.JButton();
        munis_5_la1 = new javax.swing.JLabel();
        munis_5_la3 = new javax.swing.JLabel();
        munis_5_bu1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        EDITE = new javax.swing.JButton();
        SERCHE = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ch.setBackground(new java.awt.Color(255, 255, 255));
        ch.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enter.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        enter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ch.add(enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 500, 110));

        addMan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        addMan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ch.add(addMan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 480, 110));

        tu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/pngtree-true-sign-png-png-image_1589429.png"))); // NOI18N
        ch.add(tu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 310, 80));

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("تم");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        ch.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 280, 60));

        er2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        er2.setForeground(new java.awt.Color(255, 153, 0));
        er2.setText("مهم :");
        ch.add(er2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, -1, 70));

        er.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        er.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/2.png"))); // NOI18N
        ch.add(er, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, -50, 240, 200));

        getContentPane().add(ch, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 290, 580, 290));

        sidepanel.setBackground(new java.awt.Color(255, 255, 153));
        sidepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/users4_add.png"))); // NOI18N
        sidepanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, 370, 280));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/users4_delete.png"))); // NOI18N
        sidepanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 330, 270));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/users4_edit.png"))); // NOI18N
        jLabel4.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel4AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        sidepanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 340, 290));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/view.png"))); // NOI18N
        sidepanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 240, 340, 1020));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/veiw users4.png"))); // NOI18N
        sidepanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 710, 290, 270));

        back_io.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Back.png"))); // NOI18N
        sidepanel.add(back_io, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 990, 180, 70));

        jButton5.setBackground(new java.awt.Color(0, 0, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 0, 51));
        jButton5.setText("BACK");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        sidepanel.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 970, 290, 110));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 0, 204));
        jLabel9.setText("ادوات تستخدم للتعديل علي بيانات المخدومين");
        sidepanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 300, 50));

        getContentPane().add(sidepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 1080));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 204));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("X");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1890, 0, 32, 32));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1890, 0, 32, 32));

        s1.setBackground(new java.awt.Color(51, 255, 0));
        s1.setForeground(new java.awt.Color(204, 0, 51));

        Table1.setBackground(new java.awt.Color(255, 153, 0));
        Table1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Table1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Table1.setForeground(new java.awt.Color(0, 51, 204));
        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "الاسم", "رقم الهاتف", "العنوان", "تاريخ الميلاد", "المرحله العمرية", "هل لدية مشاكل صحيه ", "معلومات عنه", "النقاط", "تاريخ الأضافة", "عمره"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table1.setRowHeight(30);
        s1.setViewportView(Table1);
        if (Table1.getColumnModel().getColumnCount() > 0) {
            Table1.getColumnModel().getColumn(9).setPreferredWidth(1);
        }

        getContentPane().add(s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 570, 1640, 510));

        del_ICON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/delete images.png"))); // NOI18N
        getContentPane().add(del_ICON, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 50, 200, 60));

        veiw_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/veiw.png"))); // NOI18N
        getContentPane().add(veiw_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 60, 680, 160));

        addresstxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addresstxt.setForeground(new java.awt.Color(255, 255, 51));
        addresstxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        addresstxt.setBorder(null);
        getContentPane().add(addresstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 300, 60));

        nametxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nametxt.setForeground(new java.awt.Color(255, 255, 51));
        nametxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nametxt.setBorder(null);
        getContentPane().add(nametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 300, 60));

        phonetxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        phonetxt.setForeground(new java.awt.Color(255, 255, 51));
        phonetxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        phonetxt.setBorder(null);
        phonetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonetxtActionPerformed(evt);
            }
        });
        getContentPane().add(phonetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 50, 300, 60));

        addICON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/add.png"))); // NOI18N
        getContentPane().add(addICON, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 580, 320, 70));

        U.setBackground(new java.awt.Color(0, 0, 153));
        U.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        U.setForeground(new java.awt.Color(204, 0, 0));
        U.setText("U");
        U.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UActionPerformed(evt);
            }
        });
        getContentPane().add(U, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 260, 50, 50));

        ok.setBackground(new java.awt.Color(0, 0, 153));
        ok.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ok.setForeground(new java.awt.Color(204, 0, 0));
        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        getContentPane().add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 260, 70, 50));

        year_it_verticalcom.setBackground(new java.awt.Color(255, 204, 0));
        year_it_verticalcom.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        year_it_verticalcom.setForeground(new java.awt.Color(204, 0, 0));
        year_it_verticalcom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "الصف الأول الثانوي", "الصف الثاني الثانوي", "الصف الثالث الثانوي" }));
        year_it_verticalcom.setBorder(null);
        year_it_verticalcom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                year_it_verticalcomActionPerformed(evt);
            }
        });
        getContentPane().add(year_it_verticalcom, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 370, 290, 60));

        yesornocom.setBackground(new java.awt.Color(255, 204, 0));
        yesornocom.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        yesornocom.setForeground(new java.awt.Color(204, 0, 0));
        yesornocom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "لا يوجد", "يوجد" }));
        yesornocom.setBorder(null);
        getContentPane().add(yesornocom, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 210, 180, 60));

        addstu.setBackground(new java.awt.Color(255, 153, 51));
        addstu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        addstu.setForeground(new java.awt.Color(255, 0, 0));
        addstu.setText("أضافة");
        addstu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(102, 255, 0), new java.awt.Color(0, 204, 51), new java.awt.Color(0, 255, 0), new java.awt.Color(0, 255, 0)));
        addstu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addstuActionPerformed(evt);
            }
        });
        getContentPane().add(addstu, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 580, 240, 70));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel8.setText("________________________________________________");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 300, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel10.setText("________________________________________________");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 80, 300, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel12.setText("________________________________________________");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 300, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 0, 51));
        jLabel13.setText("رقم الهاتف");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1520, 50, 130, 60));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 0, 51));
        jLabel14.setText("العنوان");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 250, 80, 60));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 0, 51));
        jLabel15.setText("تاريخ الميلاد");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 250, 120, 60));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel16.setText("مشاكل صحية ");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1690, 210, 210, 60));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 0, 51));
        jLabel17.setText("معلومات عن المخدوم لا تتجاوز ال 100 حرف :");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 310, 390, 60));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 0, 51));
        jLabel18.setText("الاسم");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 70, 60));

        jTextField1.setBackground(new java.awt.Color(204, 51, 255));
        jTextField1.setFont(new java.awt.Font("Sitka Subheading", 0, 1)); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 650, 100, 60));

        po_txt.setBackground(new java.awt.Color(204, 51, 255));
        po_txt.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        getContentPane().add(po_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 650, 100, 60));

        jTextField3.setBackground(new java.awt.Color(204, 51, 255));
        jTextField3.setFont(new java.awt.Font("Sitka Subheading", 0, 1)); // NOI18N
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 650, 90, 60));

        POINT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/ba2_ICON.png"))); // NOI18N
        getContentPane().add(POINT, new org.netbeans.lib.awtextra.AbsoluteConstraints(1620, 540, 260, 280));

        BACK.setBackground(new java.awt.Color(255, 51, 51));
        BACK.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        BACK.setForeground(new java.awt.Color(51, 0, 204));
        BACK.setText("POINT");
        BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKActionPerformed(evt);
            }
        });
        getContentPane().add(BACK, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 650, 310, 60));

        Health_psychological_problemstxt.setBackground(new java.awt.Color(0, 102, 204));
        Health_psychological_problemstxt.setColumns(20);
        Health_psychological_problemstxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Health_psychological_problemstxt.setLineWrap(true);
        Health_psychological_problemstxt.setRows(10);
        getContentPane().add(Health_psychological_problemstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1490, 360, 390, 290));

        ok_delete.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ok_delete.setForeground(new java.awt.Color(255, 0, 0));
        ok_delete.setText("حذف");
        ok_delete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ok_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok_deleteActionPerformed(evt);
            }
        });
        getContentPane().add(ok_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 50, 300, 60));

        ser.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ser.setForeground(new java.awt.Color(51, 0, 255));
        ser.setText("search");
        ser.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serActionPerformed(evt);
            }
        });
        getContentPane().add(ser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 50, 300, 60));

        searchEdite.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        searchEdite.setForeground(new java.awt.Color(255, 255, 51));
        searchEdite.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        searchEdite.setBorder(null);
        getContentPane().add(searchEdite, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 150, 300, 60));

        serEdLable.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        serEdLable.setForeground(new java.awt.Color(204, 0, 51));
        serEdLable.setText("اسم المخدوم");
        getContentPane().add(serEdLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 160, 150, 60));

        serEdLable2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        serEdLable2.setText("________________________________________________");
        getContentPane().add(serEdLable2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 180, 300, 30));

        sa_ICON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/save icon icon.png"))); // NOI18N
        sa_ICON.setAutoscrolls(true);
        getContentPane().add(sa_ICON, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 650, 60, 60));

        SAVE.setBackground(new java.awt.Color(255, 51, 51));
        SAVE.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        SAVE.setForeground(new java.awt.Color(51, 0, 204));
        SAVE.setText("SAVE ");
        SAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVEActionPerformed(evt);
            }
        });
        getContentPane().add(SAVE, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 650, 310, 60));

        UP_ICON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/UPDATE ICON.png"))); // NOI18N
        getContentPane().add(UP_ICON, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 650, 180, 60));

        UPDATE.setBackground(new java.awt.Color(255, 51, 51));
        UPDATE.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        UPDATE.setForeground(new java.awt.Color(51, 0, 204));
        UPDATE.setText("  UPDATE");
        UPDATE.setToolTipText("");
        UPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATEActionPerformed(evt);
            }
        });
        getContentPane().add(UPDATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 650, 310, 60));

        jDateChooser1.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooser1.setEnabled(false);
        jDateChooser1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 260, 240, 50));

        t.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        t.setBorder(null);
        getContentPane().add(t, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 260, 230, 50));

        plus_5_la.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        plus_5_la.setForeground(new java.awt.Color(51, 255, 0));
        plus_5_la.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        plus_5_la.setText("+5");
        plus_5_la.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                plus_5_laAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(plus_5_la, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 480, 100, 100));

        plus_5_la2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/ba2_ICON.png"))); // NOI18N
        getContentPane().add(plus_5_la2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 410, 220, 250));

        plus_5_bu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plus_5_buActionPerformed(evt);
            }
        });
        getContentPane().add(plus_5_bu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 520, 40, 30));

        munis_5_la1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        munis_5_la1.setForeground(new java.awt.Color(51, 255, 0));
        munis_5_la1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        munis_5_la1.setText("-5");
        getContentPane().add(munis_5_la1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 490, 80, 80));

        munis_5_la3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/ba2_ICON.png"))); // NOI18N
        getContentPane().add(munis_5_la3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, 220, 250));

        munis_5_bu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                munis_5_bu1ActionPerformed(evt);
            }
        });
        getContentPane().add(munis_5_bu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 520, 40, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/2.jpg"))); // NOI18N
        jLabel1.setText("name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 290, 210));

        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 290, 220));

        EDITE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDITEActionPerformed(evt);
            }
        });
        getContentPane().add(EDITE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 290, 240));

        SERCHE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SERCHEActionPerformed(evt);
            }
        });
        getContentPane().add(SERCHE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 730, 290, 240));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed

        jDateChooser1.setVisible(true);
        jDateChooser1.setEnabled(true);
        plus_5_bu.setVisible(false);
        plus_5_la.setVisible(false);
        plus_5_la2.setVisible(false);
        munis_5_bu1.setVisible(false);
        munis_5_la1.setVisible(false);
        munis_5_la3.setVisible(false);
        jTextField1.setVisible(false);
        po_txt.setVisible(false);
        jTextField3.setVisible(false);

        ok.setVisible(false);
        U.setVisible(false);
        t.setVisible(false);
        ser.setVisible(false);
        enter.setVisible(false);
        s1.setVisible(false);
        ok_delete.setVisible(false);
        ok_delete.setEnabled(false);
        nametxt.setVisible(true);
        phonetxt.setVisible(true);
        addresstxt.setVisible(true);
        jDateChooser1.setVisible(true);
        Health_psychological_problemstxt.setVisible(true);
        yesornocom.setVisible(true);
        year_it_verticalcom.setVisible(true);
        addstu.setVisible(true);
        jLabel8.setVisible(true);
        jLabel10.setVisible(true);
        jLabel12.setVisible(true);
        jLabel13.setVisible(true);
        jLabel14.setVisible(true);
        jLabel15.setVisible(true);
        jLabel16.setVisible(true);
        jLabel17.setVisible(true);
        jLabel18.setVisible(true);
        searchEdite.setVisible(false);
        serEdLable.setVisible(false);
        serEdLable2.setVisible(false);
        SAVE.setVisible(false);
        UPDATE.setVisible(false);
        BACK.setVisible(false);
        //---------------------------------------
        addICON.setVisible(true);
        del_ICON.setVisible(false);
        sa_ICON.setVisible(false);
        UP_ICON.setVisible(false);
        POINT.setVisible(false);
        veiw_icon.setVisible(false);
        POINT.setVisible(false);


    }//GEN-LAST:event_addActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new LOGI().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void EDITEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDITEActionPerformed

        jTextField1.setVisible(false);
        ok.setVisible(false);
        U.setVisible(false);
        t.setVisible(false);
        ser.setVisible(false);
        enter.setVisible(false);
        s1.setVisible(false);
        ok_delete.setVisible(false);
        ok_delete.setEnabled(false);
        nametxt.setVisible(false);
        phonetxt.setVisible(false);
        addresstxt.setVisible(false);
        jDateChooser1.setVisible(false);
        Health_psychological_problemstxt.setVisible(false);
        yesornocom.setVisible(false);
        addstu.setVisible(false);
        jLabel8.setVisible(false);
        jLabel10.setVisible(false);
        jLabel12.setVisible(false);
        jLabel13.setVisible(false);
        jLabel14.setVisible(false);
        jLabel15.setVisible(false);
        jLabel16.setVisible(false);
        jLabel17.setVisible(false);
        jLabel18.setVisible(false);
        addICON.setVisible(false);
        del_ICON.setVisible(false);
        sa_ICON.setVisible(false);
        POINT.setVisible(false);
        veiw_icon.setVisible(false);
        UP_ICON.setVisible(true);
        POINT.setVisible(true);
        BACK.setVisible(true);
        searchEdite.setVisible(true);
        serEdLable.setVisible(true);
        serEdLable2.setVisible(true);
        UPDATE.setVisible(true);
        year_it_verticalcom.setVisible(true);
        plus_5_bu.setVisible(true);
        plus_5_la.setVisible(true);
        plus_5_la2.setVisible(true);
        munis_5_bu1.setVisible(true);
        munis_5_la1.setVisible(true);
        munis_5_la3.setVisible(true);
        jTextField3.setVisible(true);
        po_txt.setVisible(true);

    }//GEN-LAST:event_EDITEActionPerformed

    private void SERCHEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SERCHEActionPerformed

        plus_5_bu.setVisible(false);
        plus_5_la.setVisible(false);
        plus_5_la2.setVisible(false);
        munis_5_bu1.setVisible(false);
        munis_5_la1.setVisible(false);
        munis_5_la3.setVisible(false);
        ok.setVisible(false);
        t.setVisible(false);
        U.setVisible(false);
        jTextField1.setVisible(false);
        po_txt.setVisible(false);
        jTextField3.setVisible(false);

        searchEdite.setVisible(true);
        serEdLable.setVisible(true);
        serEdLable2.setVisible(true);
        enter.setVisible(false);
        ser.setVisible(true);
        nametxt.setVisible(true);
        phonetxt.setVisible(false);
        addresstxt.setVisible(false);
        jDateChooser1.setVisible(false);
        Health_psychological_problemstxt.setVisible(false);
        yesornocom.setVisible(false);
        year_it_verticalcom.setVisible(true);
        addstu.setVisible(false);
        jLabel8.setVisible(false);
        jLabel10.setVisible(false);
        jLabel12.setVisible(true);
        jLabel13.setVisible(false);
        jLabel14.setVisible(false);
        jLabel15.setVisible(false);
        jLabel16.setVisible(false);
        jLabel17.setVisible(false);
        jLabel18.setVisible(true);
        ok_delete.setVisible(false);
        ok_delete.setEnabled(false);
        searchEdite.setVisible(false);
        serEdLable.setVisible(false);
        serEdLable2.setVisible(false);
        SAVE.setVisible(false);
        UPDATE.setVisible(false);
        BACK.setVisible(false);
        addICON.setVisible(false);
        del_ICON.setVisible(false);
        sa_ICON.setVisible(false);
        UP_ICON.setVisible(false);
        POINT.setVisible(false);
        veiw_icon.setVisible(true);
        POINT.setVisible(false);

    }//GEN-LAST:event_SERCHEActionPerformed

    private void addstuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addstuActionPerformed
        enter.setVisible(false);
        addMan.setVisible(false);
        String name = this.nametxt.getText();
        String phone = this.phonetxt.getText();
        String address = this.addresstxt.getText();
        String Health_psychological_problems = this.Health_psychological_problemstxt.getText();
        String yesorno = this.yesornocom.getSelectedItem().toString();
        String year_it_vertical = this.year_it_verticalcom.getSelectedItem().toString();

        try {

            //---------------------------------------- Date year
            SimpleDateFormat fordate = new SimpleDateFormat("dd-mm-yyyy");
            Date thisDate = new Date();
            String c2 = fordate.format(thisDate);
            Date date1 = fordate.parse(c2);
            String t = fordate.format(jDateChooser1.getDate());
            Date date2 = fordate.parse(t);
            int a = date1.getYear() - date2.getYear();

            //------------------------------------------
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection c = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "System", "123");
            PreparedStatement ps = c.prepareStatement("INSERT INTO INSERT_Served(name,phone,address,birth_date,year_it_vertical,yesorno,health_psychological_problems , Date_now ,point ,birth) VALUES(?,?,?,?,?,?,?,to_char(SYSDATE ,'dd-Mon-yyyy hh:mm:ss pm'),0," + a + ")");
            SimpleDateFormat fulldate = new SimpleDateFormat("d MMM, yyyy");
            String date = fulldate.format(jDateChooser1.getDate());
            ps.setString(1, name);
            ps.setString(2, phone);
            ps.setString(3, address);
            ps.setString(4, date);
            ps.setString(5, year_it_vertical);
            ps.setString(6, yesorno);
            ps.setString(7, Health_psychological_problems);

            PreparedStatement psco = c.prepareStatement("COMMIT");
            if (ps.executeUpdate() >= 1) {
                psco.execute();
                enter.setVisible(true);
                tu.setVisible(true);
                ch.setVisible(true);
                er.setVisible(false);
                er2.setVisible(false);
                enter.setVisible(false);
                addMan.setVisible(true);
                addMan.setText("تم اضافة مخدوم");
            } else {
                addMan.setVisible(false);
                enter.setVisible(true);
                tu.setVisible(false);
                ch.setVisible(true);
                er.setVisible(true);
                er2.setVisible(true);
                enter.setText("تأكد من صحة البيانات " + "\n" + "تأكد من صحة تاريخ الميلاد ");
            }
            ps.close();
            c.close();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
            enter.setVisible(true);
            tu.setVisible(false);
            ch.setVisible(true);
            er.setVisible(true);
            er2.setVisible(true);
            enter.setText("تأكد من صحة البيانات و " + "تأكد من صحة تاريخ الميلاد ");

        }

    }//GEN-LAST:event_addstuActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed

        plus_5_bu.setVisible(false);
        plus_5_la.setVisible(false);
        plus_5_la2.setVisible(false);
        munis_5_bu1.setVisible(false);
        munis_5_la1.setVisible(false);
        munis_5_la3.setVisible(false);
        ok.setVisible(false);
        t.setVisible(false);
        U.setVisible(false);
        jTextField1.setVisible(false);
        po_txt.setVisible(false);
        jTextField3.setVisible(false);

        enter.setVisible(false);
        ok_delete.setVisible(true);
        ok_delete.setEnabled(true);
        nametxt.setVisible(true);
        phonetxt.setVisible(false);
        addresstxt.setVisible(false);
        jDateChooser1.setVisible(false);
        Health_psychological_problemstxt.setVisible(false);
        yesornocom.setVisible(false);
        year_it_verticalcom.setVisible(true);
        addstu.setVisible(false);
        jLabel8.setVisible(false);
        jLabel10.setVisible(false);
        jLabel12.setVisible(true);
        jLabel13.setVisible(false);
        jLabel14.setVisible(false);
        jLabel15.setVisible(false);
        jLabel16.setVisible(false);
        jLabel17.setVisible(false);
        jLabel18.setVisible(true);
        s1.setVisible(false);
        searchEdite.setVisible(false);
        serEdLable.setVisible(false);
        serEdLable2.setVisible(false);
        SAVE.setVisible(false);
        UPDATE.setVisible(false);
        BACK.setVisible(false);
        addICON.setVisible(false);
        del_ICON.setVisible(true);
        sa_ICON.setVisible(false);
        UP_ICON.setVisible(false);
        POINT.setVisible(false);
        veiw_icon.setVisible(false);
    }//GEN-LAST:event_deleteActionPerformed

    private void ok_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok_deleteActionPerformed
        enter.setVisible(false);

        String name = this.nametxt.getText();
        String year_it_vertical = this.year_it_verticalcom.getSelectedItem().toString();

        try {
            enter.setVisible(false);
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection c = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "System", "123");
            PreparedStatement ps = c.prepareStatement("DELETE FROM Served WHERE name = ? and year_it_vertical = ?");
            ps.setString(1, name);
            ps.setString(2, year_it_vertical);
            ps.executeUpdate();
            PreparedStatement ps2 = c.prepareStatement("DELETE FROM INSERT_Served WHERE name = ? and year_it_vertical = ?");
            ps2.setString(1, name);
            ps2.setString(2, year_it_vertical);
            if (ps2.executeUpdate() >= 1) {
                addMan.setText("نم حذف الحساب بنجاح");
                ch.setVisible(true);
                tu.setVisible(true);
                er.setVisible(false);

            } else {
          tu.setVisible(false);
             addMan.setText("تأكد من صحة البيانات");
            ch.setVisible(true);
            er.setVisible(true);;
            }
            
            ps.close();
            c.close();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }


    }//GEN-LAST:event_ok_deleteActionPerformed

    private void serActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) Table1.getModel();
        String name = this.nametxt.getText();
        String year_it_vertical = this.year_it_verticalcom.getSelectedItem().toString();
        dtm.setRowCount(0);
        try {
            enter.setVisible(false);

            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection c = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "System", "123");
            PreparedStatement pr = c.prepareStatement("select * from INSERT_Served where name like '%" + name + "%' and year_it_vertical =?");

            pr.setString(1, year_it_vertical);
            ResultSet rs = pr.executeQuery();
            if (rs.next()) {
                s1.setVisible(true);
                String a = rs.getString("name");
                String b = rs.getString("phone");
                String cc = rs.getString("address");
                String d = rs.getString("birth_date");
                String e = rs.getString("year_it_vertical");
                String f = rs.getString("yesorno");
                String g = rs.getString("Health_psychological_problems");
                String h = rs.getString("point");
                String u = rs.getString("Date_now");
                String z = rs.getString("birth");
                String arr[] = {a, b, cc, d, e, f, g, h, u, z};
                dtm.addRow(arr);
                ch.setVisible(true);
                addMan.setVisible(true);
                addMan.setText(" تم البحث");

            }
            else
            {
            
             ch.setVisible(true);
                addMan.setText("تأكد من صحة البيانات");
                tu.setVisible(false);
                er.setVisible(true);

            }
            pr.close();
            c.close();
        } catch (ClassNotFoundException | SQLException ex) {
            enter.setText("تأكد من صحة البيانات");
            
        }


    }//GEN-LAST:event_serActionPerformed

    private void jLabel4AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel4AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4AncestorAdded

    private void BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKActionPerformed

        ok.setVisible(false);
        U.setVisible(false);

        t.setVisible(false);
        ser.setVisible(false);
        enter.setVisible(false);
        s1.setVisible(false);
        ok_delete.setVisible(false);
        ok_delete.setEnabled(false);
        nametxt.setVisible(false);
        phonetxt.setVisible(false);
        addresstxt.setVisible(false);
        jDateChooser1.setVisible(false);
        Health_psychological_problemstxt.setVisible(false);
        yesornocom.setVisible(false);
        year_it_verticalcom.setVisible(true);
        addstu.setVisible(false);
        jLabel8.setVisible(false);
        jLabel10.setVisible(false);
        jLabel12.setVisible(false);
        jLabel13.setVisible(false);
        jLabel14.setVisible(false);
        jLabel15.setVisible(false);
        jLabel16.setVisible(false);
        jLabel17.setVisible(false);
        jLabel18.setVisible(false);
        searchEdite.setVisible(true);
        serEdLable.setVisible(true);
        serEdLable2.setVisible(true);
        SAVE.setVisible(false);
        UPDATE.setVisible(true);
        String name = searchEdite.getText();
        String year_it_vertical = year_it_verticalcom.getSelectedItem().toString();
        int po = Integer.parseInt(po_txt.getText());
        addMan.setVisible(false);
        enter.setVisible(false);
        try {

            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection c = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "System", "123");
            PreparedStatement ps = c.prepareStatement("UPDATE INSERT_Served SET point = point + ?" + " where  name = ? and  year_it_vertical = ?");
            PreparedStatement com = c.prepareStatement("COMMIT WORK");
            ps.setInt(1, po);
            ps.setString(2, name);
            ps.setString(3, year_it_vertical);
            com.execute();
            if (ps.executeUpdate() >= 1) {
                addMan.setVisible(true);

                addMan.setText("تم اضافة النقاط");

                tu.setVisible(true);
                ch.setVisible(true);
                er.setVisible(false);
                er2.setVisible(false);
                com.execute();
                enter.setVisible(false);

            } else {
                tu.setVisible(false);
                ch.setVisible(true);
                er.setVisible(true);
                er2.setVisible(true);
                addMan.setVisible(true);

                addMan.setText("تأكد من صحة البيانات");

            }
            enter.setVisible(true);
            BACK.setVisible(true);
            UP_ICON.setVisible(true);
            POINT.setVisible(true);
            ps.close();
            c.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            enter.setText("تأكد من صحة البيانات");

        }

    }//GEN-LAST:event_BACKActionPerformed

    private void updateGUIComponents(ResultSet rs) throws SQLException {
        if (!rs.next()) {

        } else {
            do {

                POINT.setVisible(false);
                po_txt.setVisible(false);
                U.setVisible(true);
                t.setVisible(true);
                t.setEnabled(false);
                ser.setVisible(false);
                enter.setVisible(false);
                s1.setVisible(false);
                ok_delete.setVisible(false);
                ok_delete.setEnabled(false);
                nametxt.setVisible(true);
                phonetxt.setVisible(true);
                addresstxt.setVisible(true);
                jDateChooser1.setVisible(false);
                Health_psychological_problemstxt.setVisible(true);
                yesornocom.setVisible(true);
                year_it_verticalcom.setVisible(true);
                addstu.setVisible(false);
                jLabel8.setVisible(true);
                jLabel10.setVisible(true);
                jLabel12.setVisible(true);
                jLabel13.setVisible(true);
                jLabel14.setVisible(true);
                jLabel15.setVisible(true);
                jLabel16.setVisible(true);
                jLabel17.setVisible(true);
                jLabel18.setVisible(true);
                searchEdite.setVisible(false);
                serEdLable.setVisible(false);
                serEdLable2.setVisible(false);
                SAVE.setVisible(true);
                sa_ICON.setVisible(true);
                UP_ICON.setVisible(true);
                UPDATE.setVisible(true);
                BACK.setVisible(false);

                SimpleDateFormat fulldate = new SimpleDateFormat("d MMM, yyyy");
                nametxt.setText(rs.getString("name"));
                phonetxt.setText(rs.getString("phone"));
                addresstxt.setText(rs.getString("address"));
                t.setText(rs.getString("birth_date"));
                year_it_verticalcom.setSelectedItem(rs.getString("year_it_vertical"));
                yesornocom.setSelectedItem(rs.getString("yesorno"));
                Health_psychological_problemstxt.setText(rs.getString("Health_psychological_problems"));
                enter.setText("تم البحث");

            } while (rs.next());

        }
    }


    private void UPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATEActionPerformed

        SAVE.setVisible(false);
        String x = searchEdite.getText();
        String y = year_it_verticalcom.getSelectedItem().toString();

        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection c = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "System", "123");
            PreparedStatement pr = c.prepareStatement("select * from INSERT_Served WHERE name = ? and year_it_vertical = ?");
            pr.setString(1, x);
            pr.setString(2, y);
            ResultSet rs = pr.executeQuery();
            if (!rs.next()) {
                tu.setVisible(false);
                ch.setVisible(true);
                er.setVisible(true);
                er2.setVisible(true);

                addMan.setText("تأكد من صحه البيانات");

            } else {
                do {
                    enter.setVisible(false);
                    addMan.setText("تم البحث");
                    tu.setVisible(true);
                    ch.setVisible(true);
                    er.setVisible(false);
                    er2.setVisible(false);

                    POINT.setVisible(false);
                    po_txt.setVisible(false);
                    U.setVisible(true);
                    t.setVisible(true);
                    t.setEnabled(false);
                    ser.setVisible(false);
                    s1.setVisible(false);
                    ok_delete.setVisible(false);
                    ok_delete.setEnabled(false);
                    nametxt.setVisible(true);
                    phonetxt.setVisible(true);
                    addresstxt.setVisible(true);
                    jDateChooser1.setVisible(false);
                    Health_psychological_problemstxt.setVisible(true);
                    yesornocom.setVisible(true);
                    year_it_verticalcom.setVisible(true);
                    addstu.setVisible(false);
                    jLabel8.setVisible(true);
                    jLabel10.setVisible(true);
                    jLabel12.setVisible(true);
                    jLabel13.setVisible(true);
                    jLabel14.setVisible(true);
                    jLabel15.setVisible(true);
                    jLabel16.setVisible(true);
                    jLabel17.setVisible(true);
                    jLabel18.setVisible(true);
                    searchEdite.setVisible(false);
                    serEdLable.setVisible(false);
                    serEdLable2.setVisible(false);
                    SAVE.setVisible(true);
                    sa_ICON.setVisible(true);
                    UP_ICON.setVisible(true);
                    UPDATE.setVisible(true);
                    BACK.setVisible(false);

                    SimpleDateFormat fulldate = new SimpleDateFormat("d MMM, yyyy");
                    nametxt.setText(rs.getString("name"));
                    phonetxt.setText(rs.getString("phone"));
                    addresstxt.setText(rs.getString("address"));
                    t.setText(rs.getString("birth_date"));
                    year_it_verticalcom.setSelectedItem(rs.getString("year_it_vertical"));
                    yesornocom.setSelectedItem(rs.getString("yesorno"));
                    Health_psychological_problemstxt.setText(rs.getString("Health_psychological_problems"));

                } while (rs.next());

            }

        } catch (ClassNotFoundException | SQLException ex) {
            System.out.println(ex.getMessage());
            // Handle exception (e.g., show error message to user)
        }
    }//GEN-LAST:event_UPDATEActionPerformed

    private void UActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UActionPerformed
        jDateChooser1.setVisible(true);
        jDateChooser1.setEnabled(true);

        ok.setVisible(true);
        t.setVisible(false);
        t.setEnabled(false);

        U.setVisible(false);

    }//GEN-LAST:event_UActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        String x = searchEdite.getText();
        String year_it_vertical = this.year_it_verticalcom.getSelectedItem().toString();

        try {
            /////////////////////////////////////////////////
            SimpleDateFormat fordate = new SimpleDateFormat("dd-mm-yyyy");
            Date thisDate = new Date();
            String c2 = fordate.format(thisDate);
            Date date1 = fordate.parse(c2);
            String t = fordate.format(jDateChooser1.getDate());
            Date date2 = fordate.parse(t);
            int a = date1.getYear() - date2.getYear();
            /////////////////////////////////////////////////
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection c = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "System", "123");
            PreparedStatement br = c.prepareStatement("UPDATE INSERT_Served  SET birth_date =? , birth=" + a + "  WHERE name = ?");
            SimpleDateFormat fulldate = new SimpleDateFormat("d MMM, yyyy");
            String date = fulldate.format(jDateChooser1.getDate());
            br.setString(1, x);
            br.setString(2, date);
            br.executeUpdate();

            enter.setText("تم تعديل التاريخ");

        } catch (Exception e) {
            System.out.println(e.getMessage());

        }


    }//GEN-LAST:event_okActionPerformed

    private void SAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAVEActionPerformed
        addMan.setVisible(false);
        enter.setVisible(false);

        enter.setVisible(false);
        String name = this.nametxt.getText();
        String phone = this.phonetxt.getText();
        String address = this.addresstxt.getText();
        String Health_psychological_problems = this.Health_psychological_problemstxt.getText();
        String yesorno = this.yesornocom.getSelectedItem().toString();
        String year_it_vertical = this.year_it_verticalcom.getSelectedItem().toString();
        jTextField1.setVisible(true);
        po_txt.setVisible(true);
        jTextField3.setVisible(true);

        try {

            Class.forName("oracle.jdbc.driver.OracleDriver");

            Connection c = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "System", "123");
            PreparedStatement ps = c.prepareStatement("UPDATE INSERT_Served  SET name=?,phone =?,address =?,health_psychological_problems =?,year_it_vertical=?,yesorno=? where name = ?");
            ps.setString(1, name);
            ps.setString(2, phone);
            ps.setString(3, address);
            ps.setString(4, Health_psychological_problems);
            ps.setString(5, year_it_vertical);
            ps.setString(6, yesorno);
            ps.setString(7, name);

            ps.executeUpdate();
            tu.setVisible(true);
            ch.setVisible(true);
            er.setVisible(false);
            er2.setVisible(false);
            addMan.setVisible(true);
            ps.executeUpdate();

            addMan.setText("تم  تعديل البيانات");
            enter.setVisible(false);

            BACK.setVisible(true);
            sa_ICON.setVisible(false);
            UP_ICON.setVisible(true);
            POINT.setVisible(true);
            SAVE.setVisible(false);
            jTextField1.setVisible(false);
            ok.setVisible(false);
            U.setVisible(false);
            t.setVisible(false);
            ser.setVisible(false);
            s1.setVisible(false);
            ok_delete.setVisible(false);
            ok_delete.setEnabled(false);
            nametxt.setVisible(false);
            phonetxt.setVisible(false);
            addresstxt.setVisible(false);
            jDateChooser1.setVisible(false);
            Health_psychological_problemstxt.setVisible(false);
            yesornocom.setVisible(false);
            addstu.setVisible(false);
            jLabel8.setVisible(false);
            jLabel10.setVisible(false);
            jLabel12.setVisible(false);
            jLabel13.setVisible(false);
            jLabel14.setVisible(false);
            jLabel15.setVisible(false);
            jLabel16.setVisible(false);
            jLabel17.setVisible(false);
            jLabel18.setVisible(false);
            addICON.setVisible(false);
            del_ICON.setVisible(false);
            veiw_icon.setVisible(false);
            serEdLable.setVisible(true);
            serEdLable2.setVisible(true);
            searchEdite.setVisible(true);
            enter.setVisible(true);

            ps.close();
            c.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            enter.setText("تأكد من صحة البيانات");

        }


    }//GEN-LAST:event_SAVEActionPerformed

    private void plus_5_buActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plus_5_buActionPerformed
        addMan.setVisible(false);
        String name = this.searchEdite.getText();
        String year_it_vertical = this.year_it_verticalcom.getSelectedItem().toString();
        int s = 5;

        try {
            enter.setVisible(false);

            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection c = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "System", "123");
            PreparedStatement ps = c.prepareStatement("UPDATE INSERT_Served SET point = point + " + s + " where  name = ? and  year_it_vertical = ?");
            ps.setString(1, name);
            ps.setString(2, year_it_vertical);

            if (ps.executeUpdate() >= 1) {
                tu.setVisible(true);
                er.setVisible(false);
                er2.setVisible(false);
                ch.setVisible(true);
                addMan.setVisible(false);
                addMan.setVisible(true);

                addMan.setText("تم اضافة النقاط");
            } else {
                ch.setVisible(true);
                tu.setVisible(false);
                er.setVisible(true);
                er2.setVisible(true);
                addMan.setVisible(false);
                addMan.setVisible(true);
                addMan.setText("تأكد من صحة البيانات");
            }

            enter.setVisible(true);
            BACK.setVisible(true);
            UP_ICON.setVisible(true);
            POINT.setVisible(true);
            ps.close();
            c.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());

        }


    }//GEN-LAST:event_plus_5_buActionPerformed

    private void munis_5_bu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_munis_5_bu1ActionPerformed
        addMan.setVisible(false);

        String name = this.searchEdite.getText();
        String year_it_vertical = this.year_it_verticalcom.getSelectedItem().toString();
        int s2 = -5;

        try {
            enter.setVisible(false);

            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection c = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "System", "123");
            PreparedStatement ps = c.prepareStatement("UPDATE INSERT_Served SET point = point + " + s2 + " where  name = ? and  year_it_vertical = ?");
            ps.setString(1, name);
            ps.setString(2, year_it_vertical);

            if (ps.executeUpdate() >= 1) {
                tu.setVisible(true);
                ch.setVisible(true);
                er.setVisible(false);
                er2.setVisible(false);
                addMan.setVisible(true);

                addMan.setText("تم حذف النقاط");
            } else {
                tu.setVisible(false);
                ch.setVisible(true);
                er.setVisible(true);
                er2.setVisible(true);
                addMan.setVisible(true);

                addMan.setText("تأكد من صحة البيانات");
            }
            enter.setVisible(true);
            BACK.setVisible(true);
            UP_ICON.setVisible(true);
            POINT.setVisible(true);
            c.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());

        }


    }//GEN-LAST:event_munis_5_bu1ActionPerformed

    private void plus_5_laAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_plus_5_laAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_plus_5_laAncestorAdded

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ch.setVisible(false);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void year_it_verticalcomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_year_it_verticalcomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_year_it_verticalcomActionPerformed

    private void phonetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonetxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(data1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(data1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(data1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(data1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new data1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BACK;
    private javax.swing.JButton EDITE;
    private javax.swing.JTextArea Health_psychological_problemstxt;
    private javax.swing.JLabel POINT;
    private javax.swing.JButton SAVE;
    private javax.swing.JButton SERCHE;
    private javax.swing.JTable Table1;
    private javax.swing.JButton U;
    private javax.swing.JButton UPDATE;
    private javax.swing.JLabel UP_ICON;
    private javax.swing.JButton add;
    private javax.swing.JLabel addICON;
    private javax.swing.JLabel addMan;
    private javax.swing.JTextField addresstxt;
    private javax.swing.JButton addstu;
    private javax.swing.JLabel back_io;
    private javax.swing.JPanel ch;
    private javax.swing.JLabel del_ICON;
    private javax.swing.JButton delete;
    private javax.swing.JLabel enter;
    private javax.swing.JLabel er;
    private javax.swing.JLabel er2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton munis_5_bu1;
    private javax.swing.JLabel munis_5_la1;
    private javax.swing.JLabel munis_5_la3;
    private javax.swing.JTextField nametxt;
    private javax.swing.JButton ok;
    private javax.swing.JButton ok_delete;
    private javax.swing.JTextField phonetxt;
    private javax.swing.JButton plus_5_bu;
    private javax.swing.JLabel plus_5_la;
    private javax.swing.JLabel plus_5_la2;
    private javax.swing.JTextField po_txt;
    private javax.swing.JScrollPane s1;
    private javax.swing.JLabel sa_ICON;
    private javax.swing.JTextField searchEdite;
    private javax.swing.JButton ser;
    private javax.swing.JLabel serEdLable;
    private javax.swing.JLabel serEdLable2;
    private javax.swing.JPanel sidepanel;
    private javax.swing.JTextField t;
    private javax.swing.JLabel tu;
    private javax.swing.JLabel veiw_icon;
    private javax.swing.JComboBox<String> year_it_verticalcom;
    private javax.swing.JComboBox<String> yesornocom;
    // End of variables declaration//GEN-END:variables
}
